// src/components/ContextMenu.tsx
import React, { useEffect, useRef } from 'react';
import { useUIStore } from '../stores/ui';
import Icon from './Icon';

const ContextMenu: React.FC = () => {
  const contextMenuOpen = useUIStore((s) => s.contextMenuOpen);
  const contextMenuPosition = useUIStore((s) => s.contextMenuPosition);
  const contextFolderId = useUIStore((s) => s.contextFolderId);
  const hideContextMenu = useUIStore((s) => s.hideContextMenu);
  const openFolderModal = useUIStore((s) => s.openFolderModal);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!contextMenuOpen) return;
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) hideContextMenu();
    };
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') hideContextMenu();
    };
    document.addEventListener('click', handleClickOutside);
    document.addEventListener('keydown', handleEscape);
    return () => {
      document.removeEventListener('click', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    };
  }, [contextMenuOpen, hideContextMenu]);

  const handleNewFolder = () => { openFolderModal(); hideContextMenu(); };
  const handleRename = () => {
    if (contextFolderId) openFolderModal(contextFolderId);
    hideContextMenu();
  };

  return (
    <div
      className={`context-menu ${contextMenuOpen ? 'open' : ''}`}
      id="context-menu"
      ref={menuRef}
      style={{ left: contextMenuPosition.x, top: contextMenuPosition.y }}
    >
      <div className="ctx-item" onClick={handleNewFolder}>
        <Icon name="FolderPlus" size={10} /> New Folder
      </div>
      <div className="ctx-divider"></div>
      <div className="ctx-item" onClick={handleRename}>
        <Icon name="Edit" size={10} /> Rename
      </div>
    </div>
  );
};

export default ContextMenu;

// SolidJS/src/components/ContextMenu.tsx
import { Component, Show, createEffect, onMount, onCleanup } from 'solid-js';
import { 
  contextMenuOpen, 
  contextMenuPosition, 
  contextFolderId,
  hideContextMenu,
  openFolderModal 
} from '../stores/ui';
import Icon from './Icon';

const ContextMenu: Component = () => {
  let menuRef: HTMLDivElement | undefined;
  
  // Close on click outside or escape
  onMount(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef && !menuRef.contains(e.target as Node)) {
        hideContextMenu();
      }
    };
    
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        hideContextMenu();
      }
    };
    
    document.addEventListener('click', handleClickOutside);
    document.addEventListener('keydown', handleEscape);
    
    onCleanup(() => {
      document.removeEventListener('click', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    });
  });
  
  const handleNewFolder = () => {
    openFolderModal();
    hideContextMenu();
  };
  
  const handleRename = () => {
    const folderId = contextFolderId();
    if (folderId) {
      openFolderModal(folderId);
    }
    hideContextMenu();
  };

  return (
    <div 
      class={`context-menu ${contextMenuOpen() ? 'open' : ''}`}
      id="context-menu"
      ref={menuRef}
      style={{
        left: `${contextMenuPosition().x}px`,
        top: `${contextMenuPosition().y}px`
      }}
    >
      <div class="ctx-item" onClick={handleNewFolder}>
        <Icon name="FolderPlus" size={10} />
        New Folder
      </div>
      
      <div class="ctx-divider"></div>
      
      <div class="ctx-item" onClick={handleRename}>
        <Icon name="Edit" size={10} />
        Rename
      </div>
    </div>
  );
};

export default ContextMenu;
