// src/components/SettingsModal.tsx
import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useServiceStore } from '../stores/services';
import { useThemeStore, applyTheme, applyFont } from '../stores/themes';
import { useUIStore } from '../stores/ui';
import { shutdownDaemon, getInstalledFonts } from '../stores/socket';
import Icon from './Icon';
import Toggle from './Toggle';

const SettingsModal: React.FC = () => {
  const settings = useServiceStore((s) => s.settings);
  const updateSettings = useServiceStore((s) => s.updateSettings);
  const themes = useThemeStore((s) => s.themes);
  const settingsModalOpen = useUIStore((s) => s.settingsModalOpen);
  const closeSettingsModal = useUIStore((s) => s.closeSettingsModal);
  const openThemeCreator = useUIStore((s) => s.openThemeCreator);
  const confirm = useUIStore((s) => s.confirm);
  const selectTheme = useThemeStore((s) => s.selectTheme);

  // Port input is local-only (string) while settings.port is number|undefined
  const [portInput, setPortInput] = useState(String(settings.port ?? ''));
  const [portError, setPortError] = useState('');
  const [showShutdownConfirm, setShowShutdownConfirm] = useState(false);
  const [shuttingDown, setShuttingDown] = useState(false);

  // Font picker
  const [fontSearch, setFontSearch] = useState('');
  const [fontDropdownOpen, setFontDropdownOpen] = useState(false);
  const [allFonts, setAllFonts] = useState<string[]>([]);
  const [fontsLoading, setFontsLoading] = useState(false);
  const fontInputRef = useRef<HTMLInputElement>(null);
  const fontDropdownRef = useRef<HTMLDivElement>(null);

  const filteredFonts = fontSearch
    ? allFonts.filter((f) => f.toLowerCase().includes(fontSearch.toLowerCase()))
    : allFonts;

  const handleFontInputFocus = async () => {
    setFontDropdownOpen(true);
    if (allFonts.length === 0 && !fontsLoading) {
      setFontsLoading(true);
      try { setAllFonts(await getInstalledFonts()); } catch { useUIStore.getState().toast('Failed to load fonts', 'error'); }
      setFontsLoading(false);
    }
  };

  const handleFontSelect = (fontName: string) => {
    setFontSearch('');
    setFontDropdownOpen(false);
    applyFont(fontName);
    updateSettings({ customFont: fontName });
  };

  const handleFontReset = () => {
    setFontSearch('');
    setFontDropdownOpen(false);
    applyFont(null);
    updateSettings({ customFont: null });
  };

  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (
        fontDropdownRef.current && !fontDropdownRef.current.contains(e.target as Node) &&
        fontInputRef.current && !fontInputRef.current.contains(e.target as Node)
      ) {
        setFontDropdownOpen(false);
        setFontSearch('');
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  // Sync port input when settings.port changes from server
  useEffect(() => {
    setPortInput(String(settings.port ?? ''));
  }, [settings.port]);

  const handleThemeChange = (value: string) => {
    selectTheme(value);
  };

  const handlePortChange = (value: string) => {
    setPortInput(value);
    setPortError('');
    if (value === '') {
      updateSettings({ port: undefined });
      return;
    }
    const portNum = parseInt(value, 10);
    if (isNaN(portNum) || portNum < 1 || portNum > 65535) {
      setPortError('Port must be between 1 and 65535');
      return;
    }
    updateSettings({ port: portNum });
  };

  const handleShutdown = async () => {
    setShuttingDown(true);
    try {
      await shutdownDaemon(settings.keepServicesOnExit);
      setShowShutdownConfirm(false);
      closeSettingsModal();
    } catch {
      // Keep modal open on error - user can retry or cancel
    } finally {
      setShuttingDown(false);
    }
  };

  const handleClose = () => { setShowShutdownConfirm(false); closeSettingsModal(); };

  return (
    <AnimatePresence>
      {settingsModalOpen && (
        <div className="modal-backdrop open" id="settings-modal" onClick={(e) => {
          if ((e.target as HTMLElement).classList.contains('modal-backdrop')) handleClose();
        }}>
          <motion.div className="modal" initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }} transition={{ type: 'spring', duration: 0.38, bounce: 0.12 }}>
            <div className="modal-header">
              <div className="modal-title">Settings</div>
              <button className="modal-close" onClick={handleClose}><Icon name="X" size={14} /></button>
            </div>

            <div className="modal-body">
              <div className="form-group">
                <label>Theme</label>
                <select className="theme-select" value={settings.theme} onChange={(e) => handleThemeChange(e.target.value)}>
                  {themes.map((t) => (
                    <option key={t.id} value={t.id}>{t.name}</option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label>Port</label>
                <input type="number" className="theme-select w-[100px]" placeholder="8888" value={portInput} min={1} max={65535} onChange={(e) => handlePortChange(e.target.value)} />
                {portError ? (
                  <div className="text-[11px] text-red mt-1">{portError}</div>
                ) : (
                  <div className="text-[11px] text-text3 mt-1">Port change requires daemon restart to take effect</div>
                )}
              </div>

              <div className="form-group relative">
                <label>Font</label>
                <div className="relative">
                  <div className="flex gap-1.5 items-center">
                    <input
                      ref={fontInputRef} type="text" className="theme-select"
                      placeholder={settings.customFont || 'Search or select a font…'}
                      value={fontSearch}
                      style={settings.customFont && !fontSearch ? { fontFamily: `'${settings.customFont}', system-ui, sans-serif`, color: 'var(--text)' } : undefined}
                      onChange={(e) => setFontSearch(e.target.value)}
                      onFocus={handleFontInputFocus} autoComplete="off" spellCheck={false}
                    />
                    {settings.customFont && (
                      <button title="Reset to default font" className="shrink-0 py-[5px] px-2 bg-surface2 border border-border rounded-md text-text2 cursor-pointer text-[11px] whitespace-nowrap" onClick={handleFontReset}>
                        Reset
                      </button>
                    )}
                  </div>
                  {fontDropdownOpen && (
                    <div ref={fontDropdownRef} className="absolute top-[calc(100%+4px)] left-0 right-0 bg-surface border border-border2 rounded-lg max-h-[220px] overflow-y-auto z-[300] shadow-[0_8px_24px_rgba(0,0,0,0.4)]">
                      {fontsLoading && <div className="py-3 px-3.5 text-xs text-text3">Loading fonts…</div>}
                      {!fontsLoading && filteredFonts.length === 0 && <div className="py-3 px-3.5 text-xs text-text3">No fonts found</div>}
                      {filteredFonts.map((font) => (
                        <div
                          key={font}
                          style={{ padding: '8px 14px', cursor: 'pointer', fontSize: 13, fontFamily: `'${font}', system-ui, sans-serif`, color: settings.customFont === font ? 'var(--accent)' : 'var(--text)', background: settings.customFont === font ? 'var(--surface2)' : 'transparent', borderLeft: `2px solid ${settings.customFont === font ? 'var(--accent)' : 'transparent'}` }}
                          onMouseDown={(e) => { e.preventDefault(); handleFontSelect(font); }}
                        >
                          {font}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
                {settings.customFont && (
                  <div style={{ fontSize: 11, color: 'var(--text3)', marginTop: 6 }}>
                    Active font: <span style={{ fontFamily: `'${settings.customFont}', system-ui, sans-serif`, color: 'var(--text2)' }}>{settings.customFont}</span>
                  </div>
                )}
              </div>

              <div className="form-group">
                <label>Folder Default State</label>
                <div className="sidebar-settings-row">
                  {(['remember', 'collapsed', 'expanded'] as const).map((val) => (
                    <button key={val} className={`sidebar-opt ${settings.folderStatePreference === val ? 'active' : ''}`} onClick={() => updateSettings({ folderStatePreference: val })}>
                      {val.charAt(0).toUpperCase() + val.slice(1)}
                    </button>
                  ))}
                </div>
                <div className="text-[11px] text-text3 mt-1.5">How folders should appear when loaded</div>
              </div>

              <div className="toggle-row">
                <div>
                  <div className="toggle-label">Show folder count</div>
                  <div className="toggle-sub">Display number of items in each folder</div>
                </div>
                <Toggle on={settings.showFolderCount !== false} onChange={(v) => updateSettings({ showFolderCount: v })} label="Show folder count" />
              </div>

              <div className="toggle-row">
                <div>
                  <div className="toggle-label">WinCTL Auto-start</div>
                  <div className="toggle-sub">Start WinCTL with Windows</div>
                </div>
                <Toggle on={!!settings.autoStart} onChange={(v) => updateSettings({ autoStart: v })} label="WinCTL Auto-start" />
              </div>

              <div className="toggle-row">
                <div>
                  <div className="toggle-label">Keep services on exit</div>
                  <div className="toggle-sub">When WinCTL stops, leave managed services running</div>
                </div>
                <Toggle on={!!settings.keepServicesOnExit} onChange={(v) => updateSettings({ keepServicesOnExit: v })} label="Keep services on exit" />
              </div>

              <div className="toggle-row">
                <div>
                  <div className="toggle-label">CLI --pass auto-copy</div>
                  <div className="toggle-sub">Automatically copy password to clipboard when running winctl --pass</div>
                </div>
                <Toggle on={settings.clipboardAutoCopy !== false} onChange={(v) => updateSettings({ clipboardAutoCopy: v })} label="CLI --pass auto-copy" />
              </div>

              <div className="mt-3 pt-3 border-t border-border">
                <div className="text-[11px] text-text3 mb-2">Keyboard Shortcuts</div>
                <div className="text-[11px] text-text2 grid grid-cols-2 gap-1">
                  <span><kbd className="bg-surface2 py-px px-1 rounded-[3px]">Ctrl+K</kbd> Search</span>
                  <span><kbd className="bg-surface2 py-px px-1 rounded-[3px]">Shift+N</kbd> New service</span>
                  <span><kbd className="bg-surface2 py-px px-1 rounded-[3px]">Shift+F</kbd> New folder</span>
                  <span><kbd className="bg-surface2 py-px px-1 rounded-[3px]">Esc</kbd> Close modal</span>
                  <span><kbd className="bg-surface2 py-px px-1 rounded-[3px]">?</kbd> Settings</span>
                </div>
              </div>

              <div className="mt-3 pt-3 border-t border-border">
                <div className="text-[11px] text-text3 mb-2">Trusted Devices</div>
                {(!settings.trustedDevices || settings.trustedDevices.length === 0) ? (
                  <div className="text-xs text-text2 py-1">No registered devices.</div>
                ) : (
                  <div className="flex flex-col gap-1.5">
                    {settings.trustedDevices.map((dev) => (
                      <div key={dev.id} className="flex justify-between items-center bg-surface2 rounded-md py-1.5 px-2.5">
                        <div>
                          <div className="text-[13px] text-text">{dev.name}</div>
                          <div className="text-[10px] text-text3">
                            Registered {new Date(dev.createdAt * 1000).toLocaleDateString()}
                          </div>
                        </div>
                        <button
                          className="bg-transparent border-none text-red text-xs cursor-pointer py-1 px-2"
                          onClick={async () => {
                            if (await confirm({
                              title: 'Revoke Device',
                              message: `Revoke trust for device '${dev.name}'?`,
                              confirmLabel: 'Revoke',
                              danger: true,
                            })) {
                              const updated = settings.trustedDevices?.filter((d) => d.id !== dev.id);
                              updateSettings({ trustedDevices: updated });
                            }
                          }}
                        >
                          Revoke
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              <div className="mt-3 pt-3 border-t border-border">
                <div className="text-[11px] text-text3 mb-2">Danger Zone</div>
                {!showShutdownConfirm ? (
                  <button className="w-full p-2 bg-transparent border border-red text-red rounded-md cursor-pointer text-[13px]" onClick={() => setShowShutdownConfirm(true)}>
                    Stop WinCTL
                  </button>
                ) : (
                  <div className="bg-surface2 rounded-md py-2.5 px-3">
                    <div className="text-[13px] text-text mb-1">Stop WinCTL?</div>
                    <div className="text-[11px] text-text2 mb-2.5">
                      {settings.keepServicesOnExit ? 'WinCTL will exit. Your services will keep running.' : 'WinCTL will exit and stop all managed services.'}
                    </div>
                    <div className="flex gap-2 justify-end items-center">
                      <span className="text-xs text-text2 cursor-pointer" onClick={() => setShowShutdownConfirm(false)}>Cancel</span>
                      <button
                        className={`py-[5px] px-3 bg-red border-none text-white rounded-[5px] text-xs ${shuttingDown ? 'cursor-not-allowed opacity-60' : 'cursor-pointer'}`}
                        onClick={handleShutdown}
                        disabled={shuttingDown}
                      >
                        {shuttingDown ? 'Stopping...' : 'Confirm Stop'}
                      </button>
                    </div>
                  </div>
                )}
              </div>
            </div>

            <div className="modal-footer">
              <button className="btn-cancel" onClick={openThemeCreator}>Create Theme</button>
              <button className="btn-save" onClick={handleClose}>Close</button>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};

export default SettingsModal;

// SolidJS/src/components/SettingsModal.tsx
import { Component, createSignal, createEffect, For } from 'solid-js';
import { settings, updateSettings } from '../stores/services';
import { themes, applyTheme } from '../stores/themes';
import { settingsModalOpen, closeSettingsModal, openThemeCreator } from '../stores/ui';
import { shutdownDaemon } from '../stores/socket';
import Icon from './Icon';

const SettingsModal: Component = () => {
  const [theme, setTheme] = createSignal(settings.theme || 'dark-default');
  const [folderStatePref, setFolderStatePref] = createSignal(settings.folderStatePreference || 'remember');
  const [showFolderCount, setShowFolderCount] = createSignal(settings.showFolderCount !== false);
  const [autoStart, setAutoStart] = createSignal(settings.autoStart || false);
  const [keepServicesOnExit, setKeepServicesOnExit] = createSignal(settings.keepServicesOnExit || false);
  const [showShutdownConfirm, setShowShutdownConfirm] = createSignal(false);

  createEffect(() => {
    setTheme(settings.theme || 'dark-default');
    setFolderStatePref(settings.folderStatePreference || 'remember');
    setShowFolderCount(settings.showFolderCount !== false);
    setAutoStart(settings.autoStart || false);
    setKeepServicesOnExit(settings.keepServicesOnExit || false);
  });

  const handleBackdropClick = (e: MouseEvent) => {
    if ((e.target as HTMLElement).classList.contains('modal-backdrop')) {
      handleClose();
    }
  };

  const handleThemeChange = (value: string) => {
    setTheme(value);
    updateSettings({ theme: value });
    // Apply theme
    const selectedTheme = themes().find(t => t.id === value);
    if (selectedTheme) {
      applyTheme(selectedTheme.colors);
    }
  };

  const setFolderStatePreference = (value: 'remember' | 'collapsed' | 'expanded') => {
    setFolderStatePref(value);
    updateSettings({ folderStatePreference: value });
  };

  const toggleFolderCount = () => {
    const newValue = !showFolderCount();
    setShowFolderCount(newValue);
    updateSettings({ showFolderCount: newValue });
  };

  const toggleAutoStart = () => {
    const newValue = !autoStart();
    setAutoStart(newValue);
    updateSettings({ autoStart: newValue });
  };

  const toggleKeepServicesOnExit = () => {
    const newValue = !keepServicesOnExit();
    setKeepServicesOnExit(newValue);
    updateSettings({ keepServicesOnExit: newValue });
  };

  const handleClose = () => {
    setShowShutdownConfirm(false);
    closeSettingsModal();
  };

  return (
    <div
      class={`modal-backdrop ${settingsModalOpen() ? 'open' : ''}`}
      id="settings-modal"
      onClick={handleBackdropClick}
    >
      <div class="modal">
        <div class="modal-header">
          <div class="modal-title">Settings</div>
          <button class="modal-close" onClick={handleClose}>
            <Icon name="X" size={14} />
          </button>
        </div>

        <div class="modal-body">
          <div class="form-group">
            <label>Theme</label>
            <select
              class="theme-select"
              id="theme-select"
              onChange={(e) => handleThemeChange(e.currentTarget.value)}
            >
              <For each={themes()}>
                {(themeOption) => (
                  <option value={themeOption.id} selected={theme() === themeOption.id}>
                    {themeOption.name}
                  </option>
                )}
              </For>
            </select>
          </div>

          <div class="form-group">
            <label>Folder Default State</label>
            <div class="sidebar-settings-row">
              <button
                class={`sidebar-opt ${folderStatePref() === 'remember' ? 'active' : ''}`}
                data-value="remember"
                onClick={() => setFolderStatePreference('remember')}
              >
                Remember
              </button>
              <button
                class={`sidebar-opt ${folderStatePref() === 'collapsed' ? 'active' : ''}`}
                data-value="collapsed"
                onClick={() => setFolderStatePreference('collapsed')}
              >
                Collapsed
              </button>
              <button
                class={`sidebar-opt ${folderStatePref() === 'expanded' ? 'active' : ''}`}
                data-value="expanded"
                onClick={() => setFolderStatePreference('expanded')}
              >
                Expanded
              </button>
            </div>
            <div style="font-size: 11px; color: var(--text3); margin-top: 6px;">
              How folders should appear when loaded
            </div>
          </div>

          <div class="toggle-row">
            <div>
              <div class="toggle-label">Show folder count</div>
              <div class="toggle-sub">Display number of items in each folder</div>
            </div>
            <div
              class={`toggle ${showFolderCount() ? 'on' : ''}`}
              onClick={toggleFolderCount}
            ></div>
          </div>

          <div class="toggle-row">
            <div>
              <div class="toggle-label">WinCTL Auto-start</div>
              <div class="toggle-sub">Start WinCTL with Windows</div>
            </div>
            <div
              class={`toggle ${autoStart() ? 'on' : ''}`}
              onClick={toggleAutoStart}
            ></div>
          </div>

          <div class="toggle-row">
            <div>
              <div class="toggle-label">Keep services on exit</div>
              <div class="toggle-sub">When WinCTL stops, leave managed services running</div>
            </div>
            <div
              class={`toggle ${keepServicesOnExit() ? 'on' : ''}`}
              onClick={toggleKeepServicesOnExit}
            ></div>
          </div>

          <div style="margin-top: 12px; padding-top: 12px; border-top: 1px solid var(--border);">
            <div style="font-size: 11px; color: var(--text3); margin-bottom: 8px;">Keyboard Shortcuts</div>
            <div style="font-size: 11px; color: var(--text2); display: grid; grid-template-columns: 1fr 1fr; gap: 4px;">
              <span><kbd style="background: var(--surface2); padding: 1px 4px; border-radius: 3px;">Ctrl+K</kbd> Search</span>
              <span><kbd style="background: var(--surface2); padding: 1px 4px; border-radius: 3px;">Shift+N</kbd> New service</span>
              <span><kbd style="background: var(--surface2); padding: 1px 4px; border-radius: 3px;">Shift+F</kbd> New folder</span>
              <span><kbd style="background: var(--surface2); padding: 1px 4px; border-radius: 3px;">Esc</kbd> Close modal</span>
              <span><kbd style="background: var(--surface2); padding: 1px 4px; border-radius: 3px;">?</kbd> Settings</span>
            </div>
          </div>

          <div style="margin-top: 12px; padding-top: 12px; border-top: 1px solid var(--border);">
            <div style="font-size: 11px; color: var(--text3); margin-bottom: 8px;">Danger Zone</div>
            {!showShutdownConfirm() ? (
              <button
                style="width: 100%; padding: 8px; background: transparent; border: 1px solid var(--red, #f5524a); color: var(--red, #f5524a); border-radius: 6px; cursor: pointer; font-size: 13px;"
                onClick={() => setShowShutdownConfirm(true)}
              >
                Stop WinCTL
              </button>
            ) : (
              <div style="background: var(--surface2); border-radius: 6px; padding: 10px 12px;">
                <div style="font-size: 13px; color: var(--text); margin-bottom: 4px;">Stop WinCTL?</div>
                <div style="font-size: 11px; color: var(--text2); margin-bottom: 10px;">
                  {keepServicesOnExit()
                    ? 'WinCTL will exit. Your services will keep running.'
                    : 'WinCTL will exit and stop all managed services.'}
                </div>
                <div style="display: flex; gap: 8px; justify-content: flex-end; align-items: center;">
                  <span
                    style="font-size: 12px; color: var(--text2); cursor: pointer;"
                    onClick={() => setShowShutdownConfirm(false)}
                  >
                    Cancel
                  </span>
                  <button
                    style="padding: 5px 12px; background: var(--red, #f5524a); border: none; color: #fff; border-radius: 5px; cursor: pointer; font-size: 12px;"
                    onClick={() => shutdownDaemon(keepServicesOnExit())}
                  >
                    Confirm Stop
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        <div class="modal-footer">
          <button class="btn-cancel" onClick={openThemeCreator}>Create Theme</button>
          <button class="btn-save" onClick={handleClose}>Close</button>
        </div>
      </div>
    </div>
  );
};

export default SettingsModal;
