// SolidJS/src/components/FolderCard.tsx
import { Component, For, Show, createSignal, createEffect, onCleanup } from 'solid-js';
import { Portal } from 'solid-js/web';
import { Service, Folder, settings, startService, stopService, moveServiceToFolder } from '../stores/services';
import {
  isFolderExpanded,
  toggleFolder,
  openFolderModal,
  draggedServiceId,
  setDraggedServiceId,
  showContextMenu,
  currentView
} from '../stores/ui';
import ServiceCard from './ServiceCard';
import LogViewer from './LogViewer';
import Icon from './Icon';

interface FolderCardProps {
  folder: Folder;
  services: Service[];
}

const FolderCard: Component<FolderCardProps> = (props) => {
  const [isExpanded, setIsExpanded] = createSignal(false);
  const [isDragOver, setIsDragOver] = createSignal(false);
  // Track which service's log panel is open inside the folder overlay
  const [logService, setLogService] = createSignal<Service | null>(null);

  // Sync with store
  createEffect(() => {
    setIsExpanded(isFolderExpanded(props.folder.id));
  });

  // Close log panel when folder is closed
  createEffect(() => {
    if (!isExpanded()) setLogService(null);
  });

  createEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isExpanded() && currentView() === 'gallery') {
        if (logService()) {
          setLogService(null);
        } else {
          toggleFolder(props.folder.id);
        }
      }
    };
    document.addEventListener('keydown', handleKeyDown);
    onCleanup(() => document.removeEventListener('keydown', handleKeyDown));
  });

  const handleToggle = () => {
    toggleFolder(props.folder.id);
  };

  const handleStartAll = async (e: MouseEvent) => {
    e.stopPropagation();
    for (const s of props.services.filter(s => s.status === 'stopped')) {
      await startService(s.id);
    }
  };

  const handleStopAll = async (e: MouseEvent) => {
    e.stopPropagation();
    for (const s of props.services.filter(s => s.status === 'running')) {
      await stopService(s.id);
    }
  };

  const handleRename = (e: MouseEvent) => {
    e.stopPropagation();
    openFolderModal(props.folder.id);
  };

  const handleContextMenu = (e: MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    showContextMenu(e.clientX, e.clientY, props.folder.id);
  };

  // Drag and drop handlers
  const handleDragOver = (e: DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = () => {
    setIsDragOver(false);
  };

  const handleDrop = async (e: DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    const draggedId = draggedServiceId();
    if (draggedId) {
      await moveServiceToFolder(draggedId, props.folder.id);
    }
  };

  const serviceCount = () => props.services.length;
  const showCount = () => settings.showFolderCount !== false;

  // Called by ServiceCard when inside a folder in gallery view
  const handleLogToggle = (service: Service) => {
    setLogService(prev => prev?.id === service.id ? null : service);
  };

  // Get the latest service data reactively for the log panel
  const activeLogService = () => {
    const svc = logService();
    if (!svc) return null;
    return props.services.find(s => s.id === svc.id) ?? svc;
  };

  return (
    <div
      class={`folder-card ${isExpanded() && currentView() !== 'gallery' ? 'expanded' : ''} ${isDragOver() ? 'drag-over' : ''}`}
      id={`folder-${props.folder.id}`}
      data-folder-id={props.folder.id}
      onDragOver={handleDragOver}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
    >
      <div
        class="folder-header"
        onClick={handleToggle}
        onContextMenu={handleContextMenu}
      >
        <span class="folder-chevron">
          <Icon name="ChevronRight" size={10} />
        </span>
        <span class="folder-icon">
          <Icon name="Folder" size={12} />
        </span>
        <span class="folder-name">{props.folder.name}</span>

        <div class="folder-actions" onClick={(e) => e.stopPropagation()}>
          <button
            class="folder-action-btn start"
            title="Start All"
            onClick={handleStartAll}
          >
            <Icon name="Play" size={12} />
          </button>
          <button
            class="folder-action-btn stop"
            title="Stop All"
            onClick={handleStopAll}
          >
            <Icon name="Square" size={12} />
          </button>
          <button
            class="folder-action-btn edit"
            title="Rename"
            onClick={handleRename}
          >
            <Icon name="Edit" size={12} />
          </button>
        </div>

        <Show when={showCount()}>
          <span class={`folder-count ${!showCount() ? 'hidden' : ''}`}>
            {serviceCount()}
          </span>
        </Show>
      </div>

      <Show when={currentView() !== 'gallery'}>
        <div class="folder-body">
          <div class="folder-body-inner">
            <For each={props.services}>
              {(service) => <ServiceCard service={service} inFolder={true} />}
            </For>
            <Show when={props.services.length === 0}>
              <div style="color: var(--text3); font-size: 12px; padding: 8px; text-align: center;">
                Drag services here
              </div>
            </Show>
          </div>
        </div>
      </Show>

      <Show when={isExpanded() && currentView() === 'gallery'}>
        <Portal>
          <div
            class="modal-backdrop open"
            onClick={(e) => {
              if ((e.target as HTMLElement).classList.contains('modal-backdrop')) {
                toggleFolder(props.folder.id);
              }
            }}
            style="z-index: 200;"
          >
            {/* Unified flex-row container: folder panel + log panel side by side */}
            <div
              class={`gallery-folder-overlay${activeLogService() ? ' show-log' : ''}`}
            >
              {/* Left: folder content panel */}
              <div class="gallery-folder-panel">
                <div class="modal-header" style="flex-shrink: 0;">
                  <div class="modal-title" style="display: flex; align-items: center; gap: 8px; font-size: 18px;">
                    <span style="color: var(--accent); display: flex;"><Icon name="Folder" size={18} /></span>
                    {props.folder.name}
                    <span class="folder-count" style="position: static; transform: none; display: inline-block;">
                      {serviceCount()}
                    </span>
                  </div>
                  <button class="modal-close" onClick={handleToggle}>
                    <Icon name="X" size={16} />
                  </button>
                </div>

                <div class="modal-body" style="flex: 1; overflow-y: auto; padding: 24px; background: var(--bg);">
                  <div class="services-grid view-gallery" style="display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px;">
                    <For each={props.services}>
                      {(service) => (
                        <div class="svc-wrapper" style="margin-bottom: 0;">
                          <ServiceCard
                            service={service}
                            inFolder={true}
                            onLogToggle={handleLogToggle}
                            activeLogServiceId={logService()?.id}
                          />
                        </div>
                      )}
                    </For>
                    <Show when={props.services.length === 0}>
                      <div style="color: var(--text3); font-size: 14px; text-align: center; grid-column: 1 / -1; padding: 40px; border: 2px dashed var(--border2); border-radius: 8px;">
                        This folder is empty. Drag services here in List View.
                      </div>
                    </Show>
                  </div>
                </div>
              </div>

              {/* Right: inline log panel */}
              <Show when={activeLogService()}>
                <div class="gallery-log-panel">
                  <div class="gallery-log-header">
                    <div class="gallery-log-title">
                      <span style="color: var(--accent); display: flex;"><Icon name="Terminal" size={14} /></span>
                      {activeLogService()!.name} — Logs
                    </div>
                    <button class="modal-close" onClick={() => setLogService(null)}>
                      <Icon name="X" size={14} />
                    </button>
                  </div>
                  <div class="gallery-log-body">
                    <LogViewer
                      serviceId={activeLogService()!.id}
                      logs={activeLogService()!.recentLogs || []}
                    />
                  </div>
                </div>
              </Show>
            </div>
          </div>
        </Portal>
      </Show>
    </div>
  );
};

export default FolderCard;

// src/components/FolderCard.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { createPortal } from 'react-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  SortableContext,
  useSortable,
  verticalListSortingStrategy,
} from '@dnd-kit/sortable';
import { useDroppable } from '@dnd-kit/core';
import { CSS } from '@dnd-kit/utilities';
import { useServiceStore, type Service, type Folder } from '../stores/services';
import { useUIStore } from '../stores/ui';
import SortableService from './SortableService';
import LogViewer from './LogViewer';
import Icon from './Icon';

interface FolderCardProps {
  folder: Folder;
  services: Service[];
}

const FolderCard: React.FC<FolderCardProps> = ({ folder, services }) => {
  const settings = useServiceStore((s) => s.settings);
  const updateSettings = useServiceStore((s) => s.updateSettings);
  const startService = useServiceStore((s) => s.startService);
  const stopService = useServiceStore((s) => s.stopService);
  const openFolderModal = useUIStore((s) => s.openFolderModal);
  const showContextMenu = useUIStore((s) => s.showContextMenu);

  const expandedFolders = settings.expandedFolders || [];
  const currentView = settings.currentView || 'list';
  const showCount = settings.showFolderCount !== false;

  const isExpanded = expandedFolders.includes(folder.id);
  const [logService, setLogService] = useState<Service | null>(null);

  useEffect(() => {
    if (!isExpanded) setLogService(null);
  }, [isExpanded]);

  const toggleFolder = () => {
    const next = isExpanded
      ? expandedFolders.filter((id) => id !== folder.id)
      : [...expandedFolders, folder.id];
    updateSettings({ expandedFolders: next });
  };

  const handleStartAll = async (e: React.MouseEvent) => {
    e.stopPropagation();
    for (const s of services.filter((s) => s.status === 'stopped')) {
      await startService(s.id);
    }
  };

  const handleStopAll = async (e: React.MouseEvent) => {
    e.stopPropagation();
    for (const s of services.filter((s) => s.status === 'running')) {
      await stopService(s.id);
    }
  };

  const handleRename = (e: React.MouseEvent) => {
    e.stopPropagation();
    openFolderModal(folder.id);
  };

  const handleContextMenu = (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    showContextMenu(e.clientX, e.clientY, folder.id);
  };

  const handleLogToggle = (service: Service) => {
    setLogService((prev) => (prev?.id === service.id ? null : service));
  };

  const activeLogService = logService
    ? services.find((s) => s.id === logService.id) ?? logService
    : null;

  const sortedServices = useMemo(
    () => [...services].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0)),
    [services]
  );

  const serviceIds = sortedServices.map((s) => s.id);

  // Drop target for moving a service INTO this folder. Distinct type from the
  // folder sortable so a folder-drag never targets it.
  const { setNodeRef: setDropNodeRef, isOver } = useDroppable({
    id: `folder-drop-${folder.id}`,
    data: { type: 'folder-dropzone', folderId: folder.id }
  });

  // Makes the folder itself a sortable item (drag handle in the header).
  const {
    attributes,
    listeners,
    setNodeRef: setSortNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: folder.id, data: { type: 'folder' } });

  // One element is both the service drop target and the sortable folder node.
  const setRefs = (el: HTMLElement | null) => {
    setDropNodeRef(el);
    setSortNodeRef(el);
  };

  const sortStyle: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1,
  };

  return (
    <div
      className={`folder-card ${isExpanded && currentView !== 'gallery' ? 'expanded' : ''} ${isOver ? 'drag-over' : ''} ${isDragging ? 'dragging' : ''}`}
      id={`folder-${folder.id}`}
      data-folder-id={folder.id}
      ref={setRefs}
      style={sortStyle}
    >
      <div className="folder-header" onClick={toggleFolder} onContextMenu={handleContextMenu}>
        <span
          className="folder-drag-handle"
          title="Drag to reorder"
          onClick={(e) => e.stopPropagation()}
          {...attributes}
          {...listeners}
        >
          <Icon name="GripVertical" size={12} />
        </span>
        <span className="folder-chevron">
          <Icon name="ChevronRight" size={10} />
        </span>
        <span className="folder-icon">
          <Icon name="Folder" size={12} />
        </span>
        <span className="folder-name">{folder.name}</span>

        <div className="folder-actions" onClick={(e) => e.stopPropagation()}>
          <button className="folder-action-btn start" title="Start All" onClick={handleStartAll}>
            <Icon name="Play" size={12} />
          </button>
          <button className="folder-action-btn stop" title="Stop All" onClick={handleStopAll}>
            <Icon name="Square" size={12} />
          </button>
          <button className="folder-action-btn edit" title="Rename" onClick={handleRename}>
            <Icon name="Edit" size={12} />
          </button>
        </div>

        {showCount && (
          <span className="folder-count">{services.length}</span>
        )}
      </div>

      {/* List view body */}
      {currentView !== 'gallery' && (
        <AnimatePresence>
          {isExpanded && (
            <motion.div
              className="folder-body overflow-hidden"
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              exit={{ height: 0, opacity: 0 }}
              transition={{ duration: 0.2 }}
            >
              <div
                className="folder-body-inner min-h-10"
                style={{ outline: isOver && services.length === 0 ? '2px dashed var(--accent)' : 'none' }}
              >
                <SortableContext items={serviceIds} strategy={verticalListSortingStrategy}>
                  {sortedServices.map((service, i) => (
                    <SortableService key={service.id} service={service} inFolder index={i} />
                  ))}
                </SortableContext>
                {services.length === 0 && (
                  <div className="text-text3 text-xs p-2 text-center">
                    Drag services here
                  </div>
                )}
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      )}

      {/* Gallery view overlay — Portal */}
      {isExpanded && currentView === 'gallery' &&
        createPortal(
          <div
            className="modal-backdrop open z-[200]"
            onClick={(e) => {
              if ((e.target as HTMLElement).classList.contains('modal-backdrop')) toggleFolder();
            }}
          >
            <motion.div
              className={`gallery-folder-overlay${activeLogService ? ' show-log' : ''}`}
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              transition={{ duration: 0.2, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="gallery-folder-panel">
                <div className="modal-header shrink-0">
                  <div className="modal-title flex items-center gap-2 text-lg">
                    <span className="text-accent flex">
                      <Icon name="Folder" size={18} />
                    </span>
                    {folder.name}
                    <span className="folder-count static transform-none inline-block">
                      {services.length}
                    </span>
                  </div>
                  <button className="modal-close" onClick={toggleFolder}>
                    <Icon name="X" size={16} />
                  </button>
                </div>

                <div className="modal-body flex-1 overflow-y-auto p-6 bg-bg">
                  <div
                    className="services-grid view-gallery grid grid-cols-[repeat(auto-fill,minmax(280px,1fr))] gap-4 min-h-20"
                    style={{ outline: isOver && services.length === 0 ? '2px dashed var(--accent)' : 'none' }}
                  >
                    <SortableContext items={serviceIds} strategy={verticalListSortingStrategy}>
                      {sortedServices.map((service, i) => (
                        <SortableService
                          key={service.id}
                          service={service}
                          inFolder
                          index={i}
                          onLogToggle={handleLogToggle}
                          activeLogServiceId={logService?.id}
                        />
                      ))}
                    </SortableContext>
                    {services.length === 0 && (
                      <div className="text-text3 text-sm text-center col-span-full p-10 border-2 border-dashed border-border2 rounded-lg">
                        This folder is empty. Drag services here in List View.
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {activeLogService && (
                <div className="gallery-log-panel">
                  <div className="gallery-log-header">
                    <div className="gallery-log-title">
                      <span className="text-accent flex">
                        <Icon name="Terminal" size={14} />
                      </span>
                      {activeLogService.name} — Logs
                    </div>
                    <button className="modal-close" onClick={() => setLogService(null)}>
                      <Icon name="X" size={14} />
                    </button>
                  </div>
                  <div className="gallery-log-body">
                    <LogViewer
                      serviceId={activeLogService.id}
                      logs={activeLogService.recentLogs || []}
                    />
                  </div>
                </div>
              )}
            </motion.div>
          </div>,
          document.body
        )}
    </div>
  );
};

export default FolderCard;
